FRAME-METHOD         = 1 
FRAME-HEADER         = 2 
FRAME-BODY           = 3 
FRAME-HEARTBEAT      = 8 
FRAME-MIN-SIZE       = 4096 
FRAME-END            = 206 
REPLY-SUCCESS        = 200 
CONTENT-TOO-LARGE    = 311 # soft-error
NO-ROUTE             = 312 # soft-error
NO-CONSUMERS         = 313 # soft-error
ACCESS-REFUSED       = 403 # soft-error
NOT-FOUND            = 404 # soft-error
RESOURCE-LOCKED      = 405 # soft-error
PRECONDITION-FAILED  = 406 # soft-error
CONNECTION-FORCED    = 320 # hard-error
INVALID-PATH         = 402 # hard-error
FRAME-ERROR          = 501 # hard-error
SYNTAX-ERROR         = 502 # hard-error
COMMAND-INVALID      = 503 # hard-error
CHANNEL-ERROR        = 504 # hard-error
UNEXPECTED-FRAME     = 505 # hard-error
RESOURCE-ERROR       = 506 # hard-error
NOT-ALLOWED          = 530 # hard-error
NOT-IMPLEMENTED      = 540 # hard-error
INTERNAL-ERROR       = 541 # hard-error
